- name: Make sure we have a 'rebrain' group
  group:
    name: rebrain
    state: present

- name: Allow 'rebrain' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%rebrain'
    line: '%rebrain ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to rebrain group
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: rebrain
    append: yes
    state: present
    createhome: yes
  loop:  "{{ users }}"

- name: Add .ssh directories
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ item }}"
  loop:  "{{ users }}"

- name: Add keys
  lineinfile:
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    state: present
    create: yes
    line: "{{ auth_key }}"
    owner: "{{ item }}"
    mode: 0644
  when: auth_key is defined
  loop: "{{ users }}"

