variable "email" {}
variable "task_name" {}
variable "name" {}
variable "platform" {}
variable "zone" {}
variable "networkid" {}
variable "user" {}
variable "keyfile" {}
variable "cloud_id" {}
variable "folder_id" {}
variable "family" {}
