- name: update
  apt:
    update_cache: true
- name: Install Nginx
  apt:
    name: nginx 
    state: latest
  notify:
    - restart nginx
- name: delete default
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
- name: Apply Nginx template
  template:
    src: '{{ nginx_server }}.j2'
    dest: '{{ site_available }}/{{ nginx_server }}'
- name: Create symlink
  file:
    src: '{{ site_available }}/{{ nginx_server }}'
    dest: '{{ site_enabled }}/{{ nginx_server }}' 
    state: link
  notify:
    - reload nginx
