- name: Deploy Users and Systemd
  hosts: yandex
  remote_user: ubuntu
  become: true
  roles:
    - users
    - systemd
- name: Deploy Postgres and docker
  hosts: yandex
  remote_user: ubuntu
  roles:
    - postgres
    - docker
- name: Deploy Monitoring and Network
  hosts: yandex
  remote_user: ubuntu
  become: true
  roles:
    - jenkins
    - nginx
    - efk
    - prometheus
    - grafana
    - network
    - certs
