apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      tlsSkipVerify: true
      index: '[fluentd-]YYYY.MM.DD'
      interval: Daily
      timeField: '@timestamp'

