- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
    - certbot
    - python3-certbot-nginx
- name: "Create Certs"
  command: certbot --nginx -n -d finaldevopsrebrain.devops.rebrain.srwx.net --agree-tos --register-unsafely-without-email --no-redirect
  notify: reload nginx
- name: "Create cron renew"
  cron:
    name: "renew certs"
    minute: "0"
    hour: "0"
    day: "1"
    month: "*"
    weekday: "*"
    job: "certbot renew --dry-run"
